Номер группы, ФИО:

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

Считываем данные из файла 'ph-data.csv'. Первые три столбца будут выступать в качестве матрицы признаков объектов - создать из них новый объект X. Целевая переменная хранится в столбце с названием label - из нее создать новый объект y. Заменить все значения y, меньшие 6 (кислотная среда) на -1, большие 9 (щелочная среда) на 1, 6-9 на 0.

In [2]:
df=pd.read_csv('ph-data.csv')
df = df[['red','green','blue','label']]
df.head(3)

red  green  blue  label
0  231     27    36      0
1  250     84    36      1
2  255    164    37      2

Разбить данные на тренировочные и тестовые в соотношении 7/3. Зафиксировать random_state=5

In [3]:
X = df.iloc[:,0:3].values
X[0:3]



array([[231,  27,  36],
       [250,  84,  36],
       [255, 164,  37]], dtype=int64)

In [4]:
y=df[['label']].values.ravel()
#y.head(3)
y[0:5]

array([0, 1, 2, 3, 4], dtype=int64)

In [5]:
y[y<6] = -1
y[y>9] = 1
y[[6<=yi<=9 for yi in y]] = 0
#y[0:30]


In [6]:
X_train, X_test, y_train, y_test =\
train_test_split(X, y, test_size=0.33, random_state=5)
print(y_train[:10])
print(len(y_train))

[ 0 -1  0 -1  0 -1  0  0  1  0]
437


Создать и обучить поочередно классификаторы KNeighborsClassifier, GaussianNB, DecisionTreeClassifier. Обучить их на тренировочной выборке, оценить точность на проверочной. Попробовать изменить параметры в конструкторе n_neighbors у ближайших соседей, max_depth у дерева. Посмотреть как изменится точность предсказаний (и изменится ли).

In [7]:
clr = KNeighborsClassifier(n_neighbors=4)#Конструктор классификатора
clr.fit(X_train, y_train)#Передаём данные - объекты и их классы
y_pred = clr.predict(X_test)
print(y_pred)

accuracy_score(y_test, y_pred)


[-1  0  1  0 -1 -1  1  0  1  0  1  1 -1  1 -1  1  1  1 -1 -1  1 -1  1  1
  1  0  0 -1  1  1 -1 -1 -1  1  1  1  0 -1  1  1 -1 -1 -1  0  1  1  0  1
  1 -1  0 -1  1  0 -1  1 -1 -1 -1 -1  1  1 -1  1  1 -1  0 -1  1 -1  0  0
  1 -1  1 -1 -1 -1  1  0  0  0  1  0  0  0 -1  0  1  0 -1  0  0  1  1 -1
  1 -1  0  1 -1  0  1 -1  1  0  0  1 -1  1  0  1  1  1  1 -1 -1  1  1 -1
 -1  0 -1 -1 -1 -1 -1  1  1 -1 -1  1 -1  0 -1 -1 -1  0  1 -1  0 -1 -1  0
  0 -1 -1  1 -1 -1  0 -1  1 -1  1  0  0 -1 -1  1 -1 -1  1 -1  1 -1  0  1
  1 -1  1 -1 -1 -1  0  1  1 -1  0  0  1  0 -1  1 -1 -1 -1 -1  0 -1  0 -1
  0  1  1 -1  1 -1  0  1  1  1  1 -1  0  1  1 -1 -1 -1 -1 -1  0  0  0  1]


0.9537037037037037

In [8]:
clr = GaussianNB()
clr.fit(X_train, y_train)
y_pred = clr.predict(X_test)
print(y_pred)
accuracy_score(y_test, y_pred)

[-1  0  1  0 -1 -1  1  0  1  0  1  1 -1  1 -1  1  1  1 -1 -1  1 -1  1  1
  1  0  0 -1  1  1 -1 -1 -1  1  1  1  0 -1  1  1 -1 -1 -1  0  1  1  0  1
  1 -1  0  0  1  0 -1  1 -1 -1 -1 -1  1  1  0  1  1 -1  0 -1  1 -1  0  0
  1 -1  1 -1 -1  0  1  0  0  0  1  0  0  0 -1  0  1  0 -1  0  0  1  1 -1
  1 -1  0  1 -1  0  1 -1  1  0  0  1 -1  1  0  1  1  1  1 -1 -1  1  1 -1
 -1  0  0  0  0 -1 -1  1  1 -1  0  1  0  0 -1 -1 -1  0  1  1  0 -1 -1  0
  0  0 -1  1 -1 -1  1 -1  1 -1  1  0  0 -1 -1  1 -1 -1  1 -1  1  0  0  1
  1  0  1 -1 -1 -1  0  1  1 -1  0  0  1  0 -1  0 -1 -1 -1 -1  0  0  0 -1
  0  1  1  0  1 -1  0  1  1  1  1 -1  0  1  1 -1 -1 -1 -1 -1  0  0  0  1]


0.9351851851851852

In [9]:
clr = DecisionTreeClassifier(max_depth=3)
clr.fit(X_train, y_train)
y_pred = clr.predict(X_test)
print(y_pred)
accuracy_score(y_test, y_pred)

[ 0  0  1  0 -1 -1  1  0  1  0  1  1 -1  1 -1  1  1  1 -1 -1  1 -1  1  1
  1  0  0 -1  1  1 -1 -1 -1  1  1  1  0 -1  1  1 -1 -1 -1  0  1  1  0  1
  1 -1  0  0  1  0  0  1 -1 -1 -1 -1  1  1 -1  1  1 -1  0 -1  1 -1  1  0
  1 -1  1 -1 -1 -1  1  0  0  0  1  0  0  0 -1  0  1  0 -1  0  0  1  1 -1
  1 -1  0  1 -1  0  1 -1  1  0  0  1 -1  1  0  1  1  1  1 -1 -1  1  1 -1
 -1  0 -1 -1 -1 -1 -1  1  1 -1 -1  1 -1  0 -1 -1 -1  0  1  1  0 -1 -1  0
  0 -1 -1  1 -1 -1  1 -1  1 -1  1  0  0 -1 -1  1 -1 -1  1 -1  1 -1  0  1
  1 -1  1 -1 -1 -1  0  1  1 -1  0  0  1  0 -1  0 -1 -1 -1 -1  0 -1  0 -1
  0  1  1  0  1 -1  0  1  1  1  1 -1  0  1  1 -1 -1 -1 -1 -1  0  0  0  1]


0.9537037037037037

Выбрать из просмотренных классификаторов тот классификатор и тот параметр конструктора, который показал большую точность. Обучить его на полной выборке X, y.

In [10]:
#clr = DecisionTreeClassifier(max_depth=3)
#clr.fit(X, y)
clr = KNeighborsClassifier(n_neighbors=4)#Конструктор классификатора
clr.fit(X_train, y_train)#Передаём данные - объекты и их классы

KNeighborsClassifier(n_neighbors=4)

Проверить, какой результат вернет классификатор для следующих объектов, заданных в формате RGB:

<br>
<code style="background:rgb(255, 38, 0);color:white">[255, 38, 0]</code>
<br>
<code style="background:rgb(255, 124, 0);color:white">[255, 124, 0]</code>
<br>
<code style="background:rgb(141, 250, 0);color:black">[141, 250, 0]</code>
<br>
<code style="background:rgb(179, 68, 198);color:white">[179, 68, 198]</code>
<br>
<code style="background:rgb(111, 43, 142);color:white">[111, 43, 142]</code>

In [11]:
X_new = [[255, 38, 0],[255, 124, 0],[141, 250, 0],[179, 68, 198],[111, 43, 142]]

In [12]:
y_pred = clr.predict(X_new)
print(y_pred)


[-1 -1  0  1  1]


In [13]:
from joblib import dump
dump(clr,'olya_model.mdl')


['olya_model.mdl']

In [15]:
from joblib import load
clf=load('olya_model.mdl')
